### ISSUE TITLE
Error on heroku

### ISSUE THREAD

**Issue by VyrekXD** [pionxzh/Pornhub.js#9]
![image](https://user-images.githubusercontent.com/65917996/94439426-052c1880-0166-11eb-806b-682d95146a99.png)
This is the error when i use git push heroku main to deploy my app

**Comment by pionxzh** [comment]
could you provide the error log?

**Comment by VyrekXD** [comment]
> could you provide the error log?

i uninstall de module sorry

**Comment by darkolow** [comment]
My code have a error, local his run 100%
But when i put in heroku: 

2021-06-04T16:48:06.978394+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'webm' of undefined
2021-06-04T16:48:06.978408+00:00 app[worker.1]:     at /app/index.js:190:88
2021-06-04T16:48:06.978409+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-06-04T16:48:06.978410+00:00 app[worker.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-06-04T16:48:06.978492+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2021-06-04T16:48:06.978613+00:00 app[worker.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
